### ISSUE TITLE
Current state of project.

### ISSUE THREAD

**Issue by 0xffffa** [go-i2p/go-i2p#6]
What's the current state of the project? I'd like to hopefully piggyback off the work of others and get the router working to the pointer where it's able to handle communication.

Thank you for your hard work

**Comment by eyedeekay** [comment]
Sorry for the delay in response, but we're finally picking up speed, now. We(hkh4n and I) are working on the noise subsystem, which, if we do it right will be a provide a simple basis upon which to base our implementation of NTCP2, which will come next. At that point, we'll be able to send and recieve I2NP messages, and the next priority will probably be how those interact with core systems, probably starting with the router-wide netDb so we can discover more routers and work on things like floodfill behavior. After that, unknown but probably something to do with our first tunnel builds.

**Comment by satk0** [comment]
Hey, I am a newcomer here and would love to contribute. Could you please give me some advice on where to start?

**Comment by satk0** [comment]
Sorry for spaming, can I for instance repair this PR #5? or implement `ReadLease` and `NewLease` in `lib/common/lease/lease.go`?

**Comment by eyedeekay** [comment]
@satk0 please feel free to repair and re-create #5 to align with the new code, and welcome to the project as a contributor :)

**Comment by satk0** [comment]
Nicee, thanks for a green light !

**Comment by eyedeekay** [comment]
Relocating this here: https://github.com/orgs/go-i2p/discussions/1
